### ISSUE TITLE
Consider optimizing these for size

### ISSUE THREAD

**Issue by ocdtrekkie** [simonw/datasette-screenshots#1]
I am going to grab two of these excellent example shots for the Sandstorm package metadata. However, our metadata has to be less than 1 MB in total, and of course, one of these images is over 1.2 MB on it's own. I could resize them to a smaller size, which would also be fine, however, you may want to look into whether or not you can script some optimizations in the format.

I use a proprietary website called tinypng.com frequently, and it can produce a visibly identical image with drastically reduced file size. It describes the primary method it uses as "similar colors in your image are combined. By reducing the number of colors, 24-bit PNG files can be converted to much smaller 8-bit indexed color images." I think this can be done by something like ImageMagick which could probably be scripted into your template.

![image](https://user-images.githubusercontent.com/4399499/169072773-59dd7bc6-59bf-4ee5-aa21-ef6991eb4150.png)

**Comment by simonw** [comment]
Lossless compression is a great idea. I usually use https://squoosh.app/ and OxiPNG for this - I bet I can run that pretty easily in GitHub Actions.

https://github.com/shssoichiro/oxipng

**Comment by simonw** [comment]
Surprisingly across all of GItHub I could only find one clean example of a GitHub Action workflow that was installing and using OxiPNG: https://cs.github.com/?scopeName=All+repos&scope=&q=oxipng+path%3A.github%2Fworkflows%2F+NOT+homebrew

https://github.com/nelsonjchen/tool4comma10k/blob/e773c9ae368a571ecbc87f741fd8156ab9596e98/.github/workflows/build.yml

**Comment by simonw** [comment]
Looks like it's not yet packaged for Ubuntu:

- https://github.com/shssoichiro/oxipng/issues/69

I'm going to see if I can figure out how to use `cargo install oxipng` inside a GitHub Actions workflow.

**Comment by simonw** [comment]
OK, it looks like `cargo install` is available in a GitHub Actions default worker (I checked using the [tmate trick](https://til.simonwillison.net/github-actions/debug-tmate)).

It takes a minute or so to run though, so I should figure out how to cache it. This looks like it should work: https://github.com/actions/cache/blob/main/examples.md#rust---cargo

**Comment by simonw** [comment]
This seems to work extremely well. Here are the images my test run produced as an artifact:

173 KB (down from 235KB)

![sql-query](https://user-images.githubusercontent.com/9599/169181587-077a185d-857a-46e5-837c-15419a9986ac.png)

788KB (down from 1.14MB)

![global-power-plants](https://user-images.githubusercontent.com/9599/169181584-1ec19667-7745-4439-88ac-b80e8425bf9f.png)

216KB (down from 305KB)

![faceting](https://user-images.githubusercontent.com/9599/169181583-477b1471-6206-4b86-a3ed-0b8fbd0f8ffb.png)

**Comment by simonw** [comment]
Running that again to check that the Cargo caching works properly: https://github.com/simonw/datasette-screenshots/runs/6499588284?check_suite_focus=true

It did:

```
    Updating crates.io index
     Ignored package `oxipng v5.0.1` is already installed, use --force to override
```

**Comment by simonw** [comment]
Wrote this up as a TIL: https://til.simonwillison.net/github-actions/oxipng

**Comment by ocdtrekkie** [comment]
Nice! Glad my suggestion yielded some fun.
